### PR TITLE
Completed the keywords with "reinforcement learning", corrected an En…

### PR DESCRIPTION
**Pull request by benoit-girard**
Added missing keyword, corrected English error, bib errors (misc -> article)

### CODE REVIEW

**Comment by rougier** [comment]
What about the bibliography, I thought journal names and page numbers were also missing, no ?

**Comment by benoit-girard** [comment]
The info was there, but as the entries were registered as "misc" rather than "article", they did not show up. If recompiled properly, with this new bib, the pb should be solved.

**Comment by rougier** [comment]
Yes, that was my point, you did not add the .bib in your commit.

**Comment by benoit-girard** [comment]
Sorry. bib added & committed.

**Pull request merged**
